DMDirc/Parser

build.gradle
circle.yml
gradle/coveralls.gradle

- Execute coveralls as part of tests, not afterwards
- Update script to plugins version to allow for files that don't exist
- Use jcenter for DMDirc plugin, to stop idea complaining

Build process tidying.

---

circle.yml

Unshallow the git repository if necessary, and fetch tags.
Both of these things are useful for versioning.

Stop circle build failing.

---

irc/src/com/dmdirc/parser/irc/IRCChannelInfo.java

Hybrid seems to send a MODE message before the 324 which causes an error (https://sentry.dmdirc.com/dmdirc/dmdirc/group/306/). This fixes it.

Modes should default to "" not null

---

irc/src/com/dmdirc/parser/irc/processors/ProcessKick.java

When we moved to events, we stopped passing null in place of clients.
Instead, fake clients should be used. Apparently ProcessKick wasn't
properly updated.
Fixes issue #100

Always provide a 'kicker' client.

---

irc/src/com/dmdirc/parser/irc/WhoisResponseHandler.java

Having two separate events means the ordering isn't guaranteed.
Handle everything for 311 numerics in one handler.

Set ADDRESS and REAL_NAME property after whois.

---

common/src/com/dmdirc/parser/common/BaseChannelInfo.java
common/src/com/dmdirc/parser/events/ChannelPasswordChangedEvent.java
common/src/com/dmdirc/parser/interfaces/ChannelInfo.java
irc/src/com/dmdirc/parser/irc/IRCChannelInfo.java
irc/src/com/dmdirc/parser/irc/IRCParser.java
irc/src/com/dmdirc/parser/irc/processors/ProcessJoin.java

- Parses outgoing JOINs to try and guess keys before we get the MODE reply.
- Parsing algorithm based on Quakenet/Hybrid handling of keys.
- Keys are swallowed from the key-list for EVERY channel that is
to join, even if it is not needed, so you would need to use
"JOIN #Foo,#Bar,#Baz Foo,,Baz" to join keyed channels #Foo and #Baz.
- Key changes by mode +k and -k will be tracked.
- Ignores attempts to set the key as "*" if we know a "better" key.
- Side effect: If the key is actually set to "*" we can only learn it if that
is what we join with, or it gets changed to that from no-key.

Try to keep track of channel keys (Close Issue #108)

---

irc/src/com/dmdirc/parser/irc/IRCParser.java
irc/src/com/dmdirc/parser/irc/events/IRCDataOutEvent.java
irc/src/com/dmdirc/parser/irc/processors/ProcessJoin.java

Make ProcessJoin handle the pendingJoins queue rather than the parser itself.
(#108)

Make ProcessJoin handle the pendingJoins queue.

---

common/src/com/dmdirc/parser/events/DataInEvent.java
irc/src/com/dmdirc/parser/irc/IRCParser.java
irc/src/com/dmdirc/parser/irc/events/IRCDataInEvent.java

This gives us access to MessageTags (#19) and pre-tokenised lines in DataIn rather than everything needing to tokenise themselves.
There are probably a few other events we want to expose messagetags on that we still don't but this is a start.

Add IRCDataInEvent that presents a ReadLine object rather than just the line of data.

---

irc/src/com/dmdirc/parser/irc/outputqueue/QueueHandler.java
irc/src/com/dmdirc/parser/irc/outputqueue/QueueItem.java

Use Java8 date types for parser queue items. Fix the time check in
QueueHandler to check if the item has been queued for longer than
10 seconds, rather than if the item was created within 10 seconds
of the epoch.

Use proper dates in QueueItems, fix broken logic.

---

irc/src/com/dmdirc/parser/irc/outputqueue/OutputQueue.java
irc/src/com/dmdirc/parser/irc/outputqueue/PriorityQueueHandler.java
irc/src/com/dmdirc/parser/irc/outputqueue/QueueHandler.java
irc/src/com/dmdirc/parser/irc/outputqueue/QueueHandlerFactory.java
irc/src/com/dmdirc/parser/irc/outputqueue/SimpleRateLimitedQueueHandler.java

Handlers provide the comparator used by BlockingQueues, creating
a circular dependency.

Don't pass BlockingQueue into handlers.

---

irc/src/com/dmdirc/parser/irc/outputqueue/OutputQueue.java

I don't think there's a good reason to change it without ditching
the entire output queue.

Make QueueHandlerFactory final.

---

irc/build.gradle
irc/integ-test/com/dmdirc/parser/irc/integration/ExampleTest.java
irc/integ-test/com/dmdirc/parser/irc/integration/util/DockerContainerRule.java

Using docker we can bring up and tear down IRCds pretty trivially.
This allows us to test the parser in real-world situations.

Add framework for parser integration tests.

---

irc/src/com/dmdirc/parser/irc/outputqueue/OutputQueue.java
irc/src/com/dmdirc/parser/irc/outputqueue/QueueHandler.java
irc/src/com/dmdirc/parser/irc/outputqueue/QueueItem.java
irc/test/com/dmdirc/parser/irc/outputqueue/QueueComparatorsTest.java

Instead of having lots of objects implement Comparable or Comparator,
pass the comparator in to the PriorityBlockingQueue.
This requires recreating the queue if the QueueHandler is ever changed,
but the previous behaviour resulted in an unstable/undefined ordering,
so it's probably better this way anyway.
This means that QueueItems no longer need to know about QueueHandler,
which makes me slightly happier.

Remove chain of Comparators in output queue.

---

irc/src/main/java/com/dmdirc/parser/irc/IRCParser.java

I incorrectly specified the timezone as UTC, when it needs to be
given the local timezone (so it can convert the always-in-UTC
epoch time into the correct local time).

Fix tsirc timezone handling.

---

common/src/main/java/com/dmdirc/parser/interfaces/ProtocolDescription.java
irc/src/main/java/com/dmdirc/parser/irc/IRCProtocolDescription.java
xmpp/src/main/java/com/dmdirc/parser/xmpp/XmppProtocolDescription.java

If the user doesn't specify a port, the parser should decide what
to do itself. A single default port isn't useful to users of the
parser.

Remove default port from ProtocolDescription.

---

build.gradle
circle.yml

Circle is configured with a user/pass in secure env vars
(not exposed to builds from forks).
In theory this allows it to push master builds to artifactory's
snapshot repository.

Add config for pushing snapshots from circle.

---

irc/src/main/java/com/dmdirc/parser/irc/IRCParser.java
irc/src/main/java/com/dmdirc/parser/irc/IRCReader.java
irc/src/test/java/com/dmdirc/parser/irc/IRCReaderTest.java

Eg, allow:
```
@123@@tag=value :test ing
@tag=value @123@:test ing
```
to both represent the same message.

Support for tsirc alongside message tags. Close #149

---

common/src/main/java/com/dmdirc/parser/common/BaseParser.java
irc/src/main/java/com/dmdirc/parser/irc/IRCParser.java
irc/src/main/java/com/dmdirc/parser/irc/IRCParserCallbackManager.java

IRCParser was designed for synchronous callbacks not async events. We've moved to using an eventbus for the parser events, but for now we want to enforce that they are still used in a synchronous way rather than async for the time being to ensure that everything behaves.
(At a later date we can review if this is actually needed.)

Allow parser sub-classes to redefine the callback manager

---

irc/src/main/java/com/dmdirc/parser/irc/IRCParser.java

MessageTags time is in UTC, LocalDateTime doesn't care for the timezone
when parsing, so we were treating the UTC time as the local time rather
then adjusting from UTC to Local.
Now we adjust it properly.

Fix handling of MessageTags times when we are not at UTC.

---

irc/src/main/java/com/dmdirc/parser/irc/outputqueue/SimpleRateLimitedOutputQueue.java

After the changes to outputqueues a while back, this left SimpleRateLimitedOutputQueue broken, rather than sending lines to the server during handleQueuedItems() it was adding them back to itself and repeating this forever.

Fix SimpleRateLimitedOutputQueue endlessly requeueing lines rather than sending them.

---

common/src/main/java/com/dmdirc/parser/events/ChannelActionEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelCTCPEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelCTCPReplyEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelJoinEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelKickEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelListModeEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelMessageEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelModeChangeEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelModeMessageEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelModeNoticeEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelNamesEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelNickChangeEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelNonUserModeChangeEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelNoticeEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelOtherAwayStateEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelPartEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelPasswordChangedEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelQuitEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelSelfJoinEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelSingleModeChangeEvent.java
common/src/main/java/com/dmdirc/parser/events/ChannelUserModeChangeEvent.java

This allows clients to listen for ChannelEvents and filter on
channel names, rather than having to handle every single
individual event type.

Add base class for channel events.

---

irc/src/main/java/com/dmdirc/parser/irc/IRCReader.java

Don't throw ArrayIndexOutOfBoundsException if we get given an entirely empty line

Don't throw ArrayIndexOutOfBoundsException if we get given an entirely empty line

---

irc/src/main/java/com/dmdirc/parser/irc/IRCParser.java
irc/src/main/java/com/dmdirc/parser/irc/processors/ProcessJoin.java
irc/src/main/java/com/dmdirc/parser/irc/processors/ProcessListModes.java
irc/src/main/java/com/dmdirc/parser/irc/processors/ProcessMessage.java
irc/src/main/java/com/dmdirc/parser/irc/processors/ProcessMode.java

This commit fixes callDebugInfo in the IRCParser to not try to string.format if there are no arguments to format with.
Also converts a whole bunch of calls to callDebugInfo to pass arguments rather than using string concatenation.

Fix call debug info
